#!/usr/bin/env bash

echo "=== create bucket ==="

if [ -z "$1" ]; then
    echo "bucket name needed"
    exit 1
fi

BUCKET_NAME=$1

aws s3api create-bucket \
--bucket $BUCKET_NAME \
--output text

aws s3api get-bucket-location --bucket $BUCKET_NAME
