#!/usr/bin/env bash
echo " == delete object"

set -e

if [ -z "$1" ]; then
    echo "bucket name needed"
    exit 1
fi

BUCKET_NAME=$1

aws s3api list-objects-v2 \
--bucket $BUCKET_NAME \
--query Contents[].Key \
| jq -n '{Objects: [inputs | .[] | {Key: .}]}' > /tmp/delete-objects.json

aws s3api delete-objects --bucket $BUCKET_NAME --delete file:///tmp/delete-objects.json
