#!/usr/bin/env bash

set -e

echo " == list objects"

if [ -z "$1" ]; then
    echo "bucket name needed"
    exit 1
fi

BUCKET_NAME=$1

aws s3api list-objects-v2 \
--bucket $BUCKET_NAME \
--query Contents[].key \
| jq -n '{Objects [inputs | .[] | {Key: .}]}'