#!/usr/bin/env bash
echo " == put object"

if [ -z "$1" ]; then
    echo "bucket name needed"
    exit 1
fi

if [ -z "$2" ]; then
    echo "filename name needed"
    exit 1
fi

BUCKET_NAME=$1
FILENAME=$2

OBJECT_KEY=$(basename "$FILENAME")

aws s3api put-object \
--bucket $BUCKET_NAME \
--key $OBJECT_KEY
#--body $FILENAME \